name: lightsail
dependencies:
  - autograd
  - pytorch
  - numpy
  - matplotlib
  - jupyter
  - scipy
  - dill
  - pytest
  - nlopt
  - multiprocess
  - python
  - pip
  - pip:
    - grcwa
    - torcwa